/**
 * Default Seed Data for The Tox Technique Outreach Platform
 * 
 * Contains complete fixtures for:
 * 1. Locations
 * 2. Marketing Accounts
 * 3. Employees with 3 distinct roles (Admin, Manager, Staff)
 * 4. Account Assignments
 * 5. Master Influencers (with full normalization)
 * 6. Outreach History (including the required repeat scenario & historical records)
 */

export const INITIAL_LOCATIONS = [
  { id: 'loc-alamo', name: 'Alamo', city: 'Alamo', state: 'TX', country: 'USA', active: true },
  { id: 'loc-fairfax', name: 'Fairfax', city: 'Fairfax', state: 'VA', country: 'USA', active: true },
  { id: 'loc-denver', name: 'Denver', city: 'Denver', state: 'CO', country: 'USA', active: true },
  { id: 'loc-southlake', name: 'Southlake', city: 'Southlake', state: 'TX', country: 'USA', active: true },
  { id: 'loc-riverton', name: 'Riverton', city: 'Riverton', state: 'UT', country: 'USA', active: true },
  { id: 'loc-scottsdale', name: 'Scottsdale', city: 'Scottsdale', state: 'AZ', country: 'USA', active: true },
  { id: 'loc-chandler', name: 'Chandler', city: 'Chandler', state: 'AZ', country: 'USA', active: true },
  { id: 'loc-palmbeach', name: 'Palm Beach', city: 'Palm Beach', state: 'FL', country: 'USA', active: true },
  { id: 'loc-mckinney', name: 'McKinney', city: 'McKinney', state: 'TX', country: 'USA', active: true },
  { id: 'loc-sugarland', name: 'Sugar Land', city: 'Sugar Land', state: 'TX', country: 'USA', active: true },
];

export const INITIAL_ACCOUNTS = [
  { id: 'acc-alamo', account_name: 'Alamo', instagram_handle: 'thetoxalamo', display_name: 'The Tox Alamo', location_id: 'loc-alamo', active: true },
  { id: 'acc-fairfax', account_name: 'Fairfax', instagram_handle: 'thetoxfairfax', display_name: 'The Tox Fairfax', location_id: 'loc-fairfax', active: true },
  { id: 'acc-denver', account_name: 'Denver', instagram_handle: 'thetoxdenver', display_name: 'The Tox Denver', location_id: 'loc-denver', active: true },
  { id: 'acc-southlake', account_name: 'Southlake', instagram_handle: 'thetoxsouthlake', display_name: 'The Tox Southlake', location_id: 'loc-southlake', active: true },
  { id: 'acc-riverton', account_name: 'Riverton', instagram_handle: 'thetoxriverton', display_name: 'The Tox Riverton', location_id: 'loc-riverton', active: true },
  { id: 'acc-scottsdale', account_name: 'Scottsdale', instagram_handle: 'thetoxscottsdale', display_name: 'The Tox Scottsdale', location_id: 'loc-scottsdale', active: true },
  { id: 'acc-chandler', account_name: 'Chandler', instagram_handle: 'thetoxchandler', display_name: 'The Tox Chandler', location_id: 'loc-chandler', active: true },
  { id: 'acc-palmbeach', account_name: 'Palm Beach', instagram_handle: 'thetoxpalmbeach', display_name: 'The Tox Palm Beach', location_id: 'loc-palmbeach', active: true },
  { id: 'acc-mckinney', account_name: 'McKinney', instagram_handle: 'thetoxmckinney', display_name: 'The Tox McKinney', location_id: 'loc-mckinney', active: true },
  { id: 'acc-sugarland', account_name: 'Sugarland', instagram_handle: 'thetoxsugarland', display_name: 'The Tox Sugar Land', location_id: 'loc-sugarland', active: true },
];

export const INITIAL_EMPLOYEES = [
  {
    id: 'emp-daniyal',
    email: 'daniyal@thetoxtechnique.com',
    full_name: 'Daniyal Khan',
    role: 'admin',
    active: true,
    avatar_url: null,
    created_at: '2026-01-10T08:00:00Z',
  },
  {
    id: 'emp-ahmed',
    email: 'ahmed@thetoxtechnique.com',
    full_name: 'Ahmed Malik',
    role: 'manager',
    active: true,
    avatar_url: null,
    created_at: '2026-01-15T08:00:00Z',
  },
  {
    id: 'emp-sarah',
    email: 'sarah@thetoxtechnique.com',
    full_name: 'Sarah Jenkins',
    role: 'staff',
    active: true,
    avatar_url: null,
    created_at: '2026-02-01T08:00:00Z',
  },
  {
    id: 'emp-elena',
    email: 'elena@thetoxtechnique.com',
    full_name: 'Elena Rostova',
    role: 'staff',
    active: true,
    avatar_url: null,
    created_at: '2026-02-10T08:00:00Z',
  },
  {
    id: 'emp-jessica',
    email: 'jessica@thetoxtechnique.com',
    full_name: 'Jessica Vance',
    role: 'staff',
    active: true,
    avatar_url: null,
    created_at: '2026-03-01T08:00:00Z',
  },
  {
    id: 'emp-marcus',
    email: 'marcus@thetoxtechnique.com',
    full_name: 'Marcus Thorne',
    role: 'staff',
    active: true,
    avatar_url: null,
    created_at: '2026-03-15T08:00:00Z',
  },
  {
    id: 'emp-priya',
    email: 'priya@thetoxtechnique.com',
    full_name: 'Priya Patel',
    role: 'staff',
    active: true,
    avatar_url: null,
    created_at: '2026-04-01T08:00:00Z',
  },
];

export const INITIAL_ASSIGNMENTS = [
  // Daniyal (Admin) assigned to all accounts
  { id: 'asg-1', employee_id: 'emp-daniyal', account_id: 'acc-alamo' },
  { id: 'asg-2', employee_id: 'emp-daniyal', account_id: 'acc-fairfax' },
  { id: 'asg-3', employee_id: 'emp-daniyal', account_id: 'acc-denver' },
  { id: 'asg-4', employee_id: 'emp-daniyal', account_id: 'acc-southlake' },
  { id: 'asg-5', employee_id: 'emp-daniyal', account_id: 'acc-riverton' },
  { id: 'asg-6', employee_id: 'emp-daniyal', account_id: 'acc-scottsdale' },
  { id: 'asg-7', employee_id: 'emp-daniyal', account_id: 'acc-chandler' },
  { id: 'asg-8', employee_id: 'emp-daniyal', account_id: 'acc-palmbeach' },
  { id: 'asg-9', employee_id: 'emp-daniyal', account_id: 'acc-mckinney' },
  { id: 'asg-10', employee_id: 'emp-daniyal', account_id: 'acc-sugarland' },

  // Ahmed (Manager)
  { id: 'asg-11', employee_id: 'emp-ahmed', account_id: 'acc-alamo' },
  { id: 'asg-12', employee_id: 'emp-ahmed', account_id: 'acc-southlake' },
  { id: 'asg-13', employee_id: 'emp-ahmed', account_id: 'acc-mckinney' },
  { id: 'asg-14', employee_id: 'emp-ahmed', account_id: 'acc-sugarland' },
  { id: 'asg-15', employee_id: 'emp-ahmed', account_id: 'acc-riverton' },

  // Sarah (Staff) - 3 assigned accounts
  { id: 'asg-16', employee_id: 'emp-sarah', account_id: 'acc-alamo' },
  { id: 'asg-17', employee_id: 'emp-sarah', account_id: 'acc-southlake' },
  { id: 'asg-18', employee_id: 'emp-sarah', account_id: 'acc-fairfax' },

  // Elena (Staff) - 3 assigned accounts
  { id: 'asg-19', employee_id: 'emp-elena', account_id: 'acc-denver' },
  { id: 'asg-20', employee_id: 'emp-elena', account_id: 'acc-scottsdale' },
  { id: 'asg-21', employee_id: 'emp-elena', account_id: 'acc-chandler' },

  // Jessica (Staff)
  { id: 'asg-22', employee_id: 'emp-jessica', account_id: 'acc-palmbeach' },
  { id: 'asg-23', employee_id: 'emp-jessica', account_id: 'acc-fairfax' },

  // Marcus (Staff)
  { id: 'asg-24', employee_id: 'emp-marcus', account_id: 'acc-southlake' },
  { id: 'asg-25', employee_id: 'emp-marcus', account_id: 'acc-mckinney' },

  // Priya (Staff)
  { id: 'asg-26', employee_id: 'emp-priya', account_id: 'acc-alamo' },
  { id: 'asg-27', employee_id: 'emp-priya', account_id: 'acc-sugarland' },
];

export const INITIAL_INFLUENCERS = [
  // 1. Core example influencer from specification
  {
    id: 'inf-example',
    instagram_handle: '@example',
    normalized_handle: 'example',
    instagram_url: 'https://www.instagram.com/example/',
    display_name: 'Jessica Jane Example',
    follower_count: 45200,
    following_count: 620,
    post_count: 312,
    niche: 'Wellness & Lymphatic Health',
    city: 'Alamo',
    state: 'TX',
    primary_location_id: 'loc-alamo',
    verified: true,
    profile_status: 'active',
    is_active: true,
    source: 'manual',
    notes: 'Key target influencer for Texas market campaigns',
    created_at: '2026-08-30T10:00:00Z',
  },

  // 2. Sample TSV influencers
  {
    id: 'inf-notboredindc',
    instagram_handle: '@notboredindc',
    normalized_handle: 'notboredindc',
    instagram_url: 'https://www.instagram.com/notboredindc/',
    display_name: 'Not Bored in DC',
    follower_count: 38900,
    niche: 'City Lifestyle & Dining',
    city: 'Fairfax',
    state: 'VA',
    primary_location_id: 'loc-fairfax',
    verified: false,
    profile_status: 'active',
    is_active: true,
    source: 'historical_import',
    notes: 'Appeared under both Fairfax and Palm Beach in legacy sheet',
    created_at: '2026-08-01T00:00:00Z',
  },
  {
    id: 'inf-azfoodie',
    instagram_handle: '@azfoodie',
    normalized_handle: 'azfoodie',
    instagram_url: 'https://www.instagram.com/azfoodie/',
    display_name: 'Arizona Foodie',
    follower_count: 142000,
    niche: 'Food & Culinary',
    city: 'Scottsdale',
    state: 'AZ',
    primary_location_id: 'loc-scottsdale',
    verified: true,
    profile_status: 'active',
    is_active: true,
    source: 'historical_import',
    notes: 'Appeared under Denver & Palm Beach in legacy sheet',
    created_at: '2026-08-01T00:00:00Z',
  },
  {
    id: 'inf-tastesoftheunion',
    instagram_handle: '@tastesoftheunion',
    normalized_handle: 'tastesoftheunion',
    instagram_url: 'https://www.instagram.com/tastesoftheunion/',
    display_name: 'Tastes of Union',
    follower_count: 18500,
    niche: 'Culinary Lifestyle',
    city: 'Fairfax',
    state: 'VA',
    primary_location_id: 'loc-fairfax',
    verified: false,
    profile_status: 'active',
    is_active: true,
    source: 'historical_import',
    created_at: '2026-08-01T00:00:00Z',
  },
  {
    id: 'inf-willworkforfashion',
    instagram_handle: '@willworkforfashion',
    normalized_handle: 'willworkforfashion',
    instagram_url: 'https://www.instagram.com/willworkforfashion/',
    display_name: 'Will Work For Fashion',
    follower_count: 24100,
    niche: 'Fashion & Beauty',
    city: 'Palm Beach',
    state: 'FL',
    primary_location_id: 'loc-palmbeach',
    verified: false,
    profile_status: 'active',
    is_active: true,
    source: 'historical_import',
    created_at: '2026-08-01T00:00:00Z',
  },
  {
    id: 'inf-thatothetallgirl',
    instagram_handle: '@thatothetallgirl',
    normalized_handle: 'thatothetallgirl',
    instagram_url: 'https://www.instagram.com/thatothetallgirl/',
    display_name: 'That Other Tall Girl',
    follower_count: 12400,
    niche: 'Fashion',
    city: 'Denver',
    state: 'CO',
    primary_location_id: 'loc-denver',
    verified: false,
    profile_status: 'active',
    is_active: true,
    source: 'historical_import',
    created_at: '2026-08-01T00:00:00Z',
  },
  {
    id: 'inf-mariisoko',
    instagram_handle: '@mariisoko',
    normalized_handle: 'mariisoko',
    instagram_url: 'https://www.instagram.com/mariisoko/',
    display_name: 'Marii Soko',
    follower_count: 53100,
    niche: 'Beauty & Skincare',
    city: 'Palm Beach',
    state: 'FL',
    primary_location_id: 'loc-palmbeach',
    verified: false,
    profile_status: 'active',
    is_active: true,
    source: 'historical_import',
    created_at: '2026-08-01T00:00:00Z',
  },
  {
    id: 'inf-emilyanngemma',
    instagram_handle: '@emilyanngemma',
    normalized_handle: 'emilyanngemma',
    instagram_url: 'https://www.instagram.com/emilyanngemma/',
    display_name: 'Emily Ann Gemma',
    follower_count: 985000,
    niche: 'Luxury & Lifestyle',
    city: 'Dallas',
    state: 'TX',
    primary_location_id: 'loc-southlake',
    verified: true,
    profile_status: 'active',
    is_active: true,
    source: 'historical_import',
    created_at: '2026-08-01T00:00:00Z',
  },
  {
    id: 'inf-bresheppard',
    instagram_handle: '@bresheppard',
    normalized_handle: 'bresheppard',
    instagram_url: 'https://www.instagram.com/bresheppard/',
    display_name: 'Bre Sheppard',
    follower_count: 310000,
    niche: 'Travel & Wellness',
    city: 'Scottsdale',
    state: 'AZ',
    primary_location_id: 'loc-scottsdale',
    verified: true,
    profile_status: 'active',
    is_active: true,
    source: 'historical_import',
    created_at: '2026-08-01T00:00:00Z',
  },
  {
    id: 'inf-lottieweaver',
    instagram_handle: '@lottieweaver',
    normalized_handle: 'lottieweaver',
    instagram_url: 'https://www.instagram.com/lottieweaver/',
    display_name: 'Lottie Weaver',
    follower_count: 145000,
    niche: 'Family & Lifestyle',
    city: 'Chandler',
    state: 'AZ',
    primary_location_id: 'loc-chandler',
    verified: true,
    profile_status: 'active',
    is_active: true,
    source: 'historical_import',
    created_at: '2026-08-01T00:00:00Z',
  },
];

export const INITIAL_OUTREACH = [
  // ============================================================================
  // CRITICAL SEEDED SCENARIO (FROM SPECIFICATION):
  // 1. Daniyal -> Alamo -> @example -> Sept 1
  // 2. Ahmed -> McKinney -> @example -> Sept 3 (Legitimate cross-account!)
  // 3. Daniyal -> Alamo -> @example -> Oct 8 (REPEAT SAME ACCOUNT!)
  // ============================================================================
  {
    id: 'out-1',
    influencer_id: 'inf-example',
    account_id: 'acc-alamo',
    employee_id: 'emp-daniyal',
    submitted_at: '2026-09-01T14:30:00Z',
    outreach_date: '2026-09-01T14:30:00Z',
    is_repeat_same_account: false,
    repeat_count_for_account: 0,
    previous_outreach_id: null,
    status: 'Contacted',
    notes: 'Initial outreach for Q3 Lymphatic Drainage campaign via Alamo IG account.',
    source: 'submission',
    created_at: '2026-09-01T14:30:00Z',
  },
  {
    id: 'out-2',
    influencer_id: 'inf-example',
    account_id: 'acc-mckinney',
    employee_id: 'emp-ahmed',
    submitted_at: '2026-09-03T16:15:00Z',
    outreach_date: '2026-09-03T16:15:00Z',
    is_repeat_same_account: false, // CROSS-ACCOUNT LEGITIMATE! Not repeat!
    repeat_count_for_account: 0,
    previous_outreach_id: null,
    status: 'Contacted',
    notes: 'Cross-account regional outreach from McKinney account. Legitimate touchpoint.',
    source: 'submission',
    created_at: '2026-09-03T16:15:00Z',
  },
  {
    id: 'out-3',
    influencer_id: 'inf-example',
    account_id: 'acc-alamo',
    employee_id: 'emp-daniyal',
    submitted_at: '2026-10-08T11:00:00Z',
    outreach_date: '2026-10-08T11:00:00Z',
    is_repeat_same_account: true, // SAME ACCOUNT REPEAT!
    repeat_count_for_account: 1,
    previous_outreach_id: 'out-1',
    status: 'Follow-up',
    notes: 'Second follow-up from Alamo account. Detected as repeat outreach.',
    source: 'submission',
    created_at: '2026-10-08T11:00:00Z',
  },

  // ============================================================================
  // HISTORICAL RECORDS (MISSING DATES — NULL)
  // Demonstrates "Date unavailable / Historical import"
  // ============================================================================
  {
    id: 'out-4',
    influencer_id: 'inf-notboredindc',
    account_id: 'acc-fairfax',
    employee_id: null,
    submitted_at: '2026-08-01T00:00:00Z',
    outreach_date: null, // Legacy date unavailable!
    is_repeat_same_account: false,
    repeat_count_for_account: 0,
    previous_outreach_id: null,
    status: 'Contacted',
    notes: 'Historical record imported from Sheet1.tsv (Fairfax column)',
    source: 'historical_import',
    created_at: '2026-08-01T00:00:00Z',
  },
  {
    id: 'out-5',
    influencer_id: 'inf-notboredindc',
    account_id: 'acc-palmbeach',
    employee_id: null,
    submitted_at: '2026-08-01T00:00:00Z',
    outreach_date: null, // Legacy date unavailable!
    is_repeat_same_account: false,
    repeat_count_for_account: 0,
    previous_outreach_id: null,
    status: 'Contacted',
    notes: 'Historical record imported from Sheet1.tsv (Palm Beach column)',
    source: 'historical_import',
    created_at: '2026-08-01T00:00:00Z',
  },
  {
    id: 'out-6',
    influencer_id: 'inf-azfoodie',
    account_id: 'acc-denver',
    employee_id: null,
    submitted_at: '2026-08-01T00:00:00Z',
    outreach_date: null,
    is_repeat_same_account: false,
    repeat_count_for_account: 0,
    previous_outreach_id: null,
    status: 'Contacted',
    notes: 'Historical record imported from Sheet1.tsv (Denver column)',
    source: 'historical_import',
    created_at: '2026-08-01T00:00:00Z',
  },
  {
    id: 'out-7',
    influencer_id: 'inf-azfoodie',
    account_id: 'acc-palmbeach',
    employee_id: null,
    submitted_at: '2026-08-01T00:00:00Z',
    outreach_date: null,
    is_repeat_same_account: false,
    repeat_count_for_account: 0,
    previous_outreach_id: null,
    status: 'Contacted',
    notes: 'Historical record imported from Sheet1.tsv (Palm Beach column)',
    source: 'historical_import',
    created_at: '2026-08-01T00:00:00Z',
  },
  {
    id: 'out-8',
    influencer_id: 'inf-tastesoftheunion',
    account_id: 'acc-fairfax',
    employee_id: 'emp-sarah',
    submitted_at: '2026-09-09T09:15:00Z',
    outreach_date: '2026-09-09T09:15:00Z',
    is_repeat_same_account: false,
    repeat_count_for_account: 0,
    previous_outreach_id: null,
    status: 'Contacted',
    notes: 'Direct outreach for Fall event invitation',
    source: 'submission',
    created_at: '2026-09-09T09:15:00Z',
  },
  {
    id: 'out-9',
    influencer_id: 'inf-emilyanngemma',
    account_id: 'acc-southlake',
    employee_id: 'emp-sarah',
    submitted_at: '2026-09-09T14:40:00Z',
    outreach_date: '2026-09-09T14:40:00Z',
    is_repeat_same_account: false,
    repeat_count_for_account: 0,
    previous_outreach_id: null,
    status: 'Replied',
    notes: 'Replied expressing interest in body contouring session.',
    source: 'submission',
    created_at: '2026-09-09T14:40:00Z',
  },
  {
    id: 'out-10',
    influencer_id: 'inf-bresheppard',
    account_id: 'acc-scottsdale',
    employee_id: 'emp-elena',
    submitted_at: '2026-09-09T17:05:00Z',
    outreach_date: '2026-09-09T17:05:00Z',
    is_repeat_same_account: false,
    repeat_count_for_account: 0,
    previous_outreach_id: null,
    status: 'Interested',
    notes: 'Booked consultation for Scottsdale location.',
    source: 'submission',
    created_at: '2026-09-09T17:05:00Z',
  },
];

export const INITIAL_SETTINGS = {
  organization_name: 'The Tox Technique',
  default_timezone: 'America/Chicago',
  pagination_limit: 25,
  repeat_warning_enabled: true,
  meta_api_configured: false,
};
